{% set version = "1.44" %}

package:
  name: wayland-protocols
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/archive/{{ version }}/wayland-protocols-{{ version }}.tar.bz2
  sha256: 4bc328e7c879c196d623b95849669cd1d6e48756e049663ff2a355522bede3c4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - meson
    - ninja
    - pkg-config
  host:
    - wayland

test:
  requires:
    - pkg-config
  commands:
    # check that the .pc file is installed correctly
    - pkg-config --exists wayland-protocols
    # check that a protocol can be found from path retrieved from pkg-config
    - test -f `pkg-config --variable=pkgdatadir --dont-define-prefix wayland-protocols`/stable/xdg-shell/xdg-shell.xml

about:
  home: https://gitlab.freedesktop.org/wayland/wayland-protocols
  summary: Protocol files for the Wayland rendering architecture
  description: |
    wayland-protocols contains Wayland protocols that add functionality not
    available in the Wayland core protocol. Such protocols either add
    completely new functionality, or extend the functionality of some other
    protocol either in Wayland core, or some other protocol in
    wayland-protocols.

    A protocol in wayland-protocols consists of a directory containing a set
    of XML files containing the protocol specification, and a README file
    containing detailed state and a list of maintainers.
  license: MIT
  license_family: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - ryanvolz
